export enum CoreRoutes {
    Home = 'home',
    Login = 'login',
    Register = 'register',
    Terms = 'terms',
    Splash = 'splash',
    About = 'about',
    Privacy = 'privacy',
    Stats = 'stats',
    Help = 'help',
    Blog = 'blog',
    Bookmarks = 'bookmarks',
    Dashboard = 'dashboard',
    Friends = 'friends',
    Groups = 'groups',
    Invite = 'invite',
    Members = 'members',
    Messages = 'messages',
    Missions = 'missions',
    NewsFeed = 'newsfeed',
    Profile = 'profile',
    Search = 'search',
    Settings = 'settings',
    TheWire = 'thewire',
    Unauthorized = 'unauthorized',
    Forbidden = 'forbidden',
    GCtools ='gctools',
}