Set Home to //*[@id="gcc-header-home-btn"]
Set Network to //*[@id="gcc-header-network-btn"]
Set Groups to //*[@id="gcc-header-groups-btn"]
Set Jobs to //*[@id="gcc-header-jobs-btn"]
Set Support to //*[@id="gcc-header-support-btn"]
Set Search to //*[@id="gcc-header-search-btn"]
Set Messages to //*[@id="gcc-header-messages-btn"]
Set Notifications to //*[@id="gcc-header-notifications-btn"]
Set Profile to //*[@id="gcc-header-profile-btn"]
Set Language to //*[@id="gcc-header-change-language"]
Set English to //*[@id="gcc-language-selector-btn-en"]
Set French to //*[@id="gcc-language-selector-btn-fr"]
Set About to //*[@id="gcc-footer-about-btn"]
Set GCtools to //*[@id="gcc-footer-gctools-btn"]
Set Statistics to //*[@id="gcc-footer-statistics-btn"]
Set Privacy to //*[@id="gcc-footer-privacy-btn"]
Set Terms to //*[@id="gcc-footer-terms-btn"]
Set FAQs to //*[@id="gcc-footer-faqs-btn"]
Set Help to //*[@id="gcc-footer-support-btn"]
Set Events to //*[@id="gcc-events-more-events"]
Set ConfirmEvent to //*[contains(@ng-reflect-message, "Confirm event")]
Set RemoveConfirmationEvent to //*[contains(@ng-reflect-message, "Remove confirmation")]
Set DeclineEvent to //*[contains(@ng-reflect-message, "Decline event")]
Set RescindDeclinationEvent to //*[contains(@ng-reflect-message, "Rescind declination")]
Set SmallEventRouter to //*[contains(@ng-reflect-router-link, '/events/0')]
Set LargeEventRouter to //*[contains(@ng-reflect-router-link, '/events/0')]