Set home to http://localhost:4200/
Set support to https://support.gccollab.ca/en/support/home
Set about to http://localhost:4200/about
Set gctools to https://github.com/gctools-outilsgc
Set privacy to http://localhost:4200/privacy
Set statistics to http://localhost:4200/stats
Set terms to http://localhost:4200/terms
Set events to http://localhost:4200/events
Set eventsdescription to http://localhost:4200/events/0
Set connections to http://localhost:4200/connections
